apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: rampini-rag

data:
  CHAT_MODEL_ENDPOINT: "https://10-38-62-49.sslip.nutanixdemo.com/enterpriseai/v1/chat/completions"
  CHAT_MODEL: "test-endpoint"

  NAI_ENDPOINT: "https://10-38-62-49.sslip.nutanixdemo.com/enterpriseai/v1/"
  EMBED_MODEL: "test-model-embd-ept"

  MILVUS_URI: "https://milvus-adminuser05-10-38-62-50.sslip.nutanixdemo.com"
  MILVUS_DATABASE: "test"
  MILVUS_COLLECTION: "test_collection4"

  MEDIA_DIR: "media"
  RAG_DOCS_DIR: "media/rag_docs"