apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: rampini
type: Opaque
stringData:
  CHAT_MODEL_API_KEY: "f1fe4d3d-f38e-4237-967c-7ba4a8d9f66a"
  NAI_API_KEY: "598b8347-b712-46ea-95b3-bc678b9d400b"