apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: rampini
type: Opaque
stringData:
  CHAT_MODEL_API_KEY: "dab1cf05-8271-411b-9549-ed464b67afe6"
  NAI_API_KEY: "dab1cf05-8271-411b-9549-ed464b67afe6"