version: "3.9"
services:
  backend-service:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: mdgolammostofa705/rampini-backend:v2
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    environment:
      PYTHONUNBUFFERED: "1"

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        BACKEND_URL: http://backend-service:8000
    image: mdgolammostofa705/rampini-frontend:v4
    ports:
      - "3000:3000"
    env_file:
      - ./frontend/.env
    environment:
      NODE_ENV: production
      BACKEND_URL: http://backend-service:8000
    depends_on:
      - backend-service
